/*============================================================================
  HDRITools - High Dynamic Range Image Tools
  Copyright 2008-2011 Program of Computer Graphics, Cornell University

  Distributed under the OSI-approved MIT License (the "License");
  see accompanying file LICENSE for details.

  This software is distributed WITHOUT ANY WARRANTY; without even the
  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the License for more information.
 ----------------------------------------------------------------------------- 
 Primary author:
     Edgar Velazquez-Armendariz <cs#cornell#edu - eva5>
============================================================================*/

package edu.cornell.graphics.exr;

import java.io.IOException;

/**
 * This class represents the exceptions generated by error while using
 * the native OpenEXR library.
 * 
 * @author edgar
 *
 */
public class EXRIOException extends IOException {

    private static final long serialVersionUID = 1L;

    public EXRIOException(){}
    public EXRIOException(String message) {
        super(message);
    }
}
